modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="meowing"
version="1.0"
displayName="Meowing"
authors="Kubus"
description='''
Simple meowing mod
'''

[[dependencies.meowing]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.meowing]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"